#!/bin/bash

echo Creating copy of source

cp mouse-damper.py mousedamper.pyx
echo Generating mousedamper.c using cython

cython3 mousedamper.pyx --embed
echo Compiling into binary

gcc -Os $(pkg-config python3 --cflags) -o mouse-damper  mousedamper.c $(pkg-config python3 --libs)
echo Changing owner to root and setting setuid bit on mouse-damper binary

sudo chown root:root mouse-damper
sudo chmod u+s mouse-damper
echo
echo Run ./mouse-damper-launch
