#!/usr/bin/env python3

import sys
import os
import setproctitle
import signal
import subprocess

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

settings = Gtk.Settings.get_default()
double_click_time = settings.get_property("gtk-double-click-time")
double_click_distance = settings.get_property("gtk-double-click-distance")
drag_threshold = settings.get_property("gtk-dnd-drag-threshold")
verbose = len(sys.argv) == 2 and sys.argv[1] == "verbose"

res = subprocess.run([os.path.join(os.getcwd(), "mouse-damper"),
                      "verbose" if verbose else "terse",
                      str(double_click_time),
                      str(double_click_distance),
                      str(drag_threshold)])

exit(res.returncode)